---
sessions: 首页
micros: 动态
images: 作品
events:
  name: 活动
  second:
    每日一拍: events
    快拍城市: events
    divider0: divider
    我的同城: events
    发现同城: events
    divider1: divider
    正在进行的活动: events
    已经结束的活动: events
# works:
#   name: 作品
#   second:
#     编辑推荐: works
#     每日精选: works
#     最新上传: works
#     热门作品: works
rs:
  name: 推荐
  second:
    每天看世界最好的照片: rs
    月月评: rs
    影展: rs
    摄影师: rs
groups:
  name: 圈子
  second:
    我的圈子: groups
    发现圈子: groups