---
sets:
  name: 个人设置
  icon: wrench
  small:
  navs:
    /my/set/basic: 基本资料
    /my/set/avatar: 头像设置
    /my/set/security: 安全设置
    #/my/set/privacy: 隐私设置
    /my/set/push: 推送设置
    /my/set/others: 同步网站
  icons: {}
  smalls: {}
albums:
  name: 我的相册
  icon: picture
  small:
  navs: {}
  icons: {}
  smalls: {}
msgs:
  name: 私信&通知
  icon: envelope
  small:
  navs:
    /my/msgs: 私信
    # mails:
    #   /my/msgs: 全部私信
    #   /my/msgs/read: 已读私信
    #   /my/msgs/unread: 未读私信
    #   /my/msgs/trash: 垃圾私信
    /my/msgs/new: 给关注的人写信
    /my/msgs/notices: 网站通知
  icons: 
    new: edit
    notices: bullhorn
  smalls: {}